2025-08-18 12:41:32,843 [INFO] Step-1: Folder created: uploads/29c97177-75dd-4433-a2e1-3999d6c8303a
2025-08-18 12:41:41,079 [INFO] Using Python executable: venv/bin/python3
2025-08-18 12:41:41,079 [INFO] Step-2: File sent {'questions.txt': 'uploads/29c97177-75dd-4433-a2e1-3999d6c8303a/questions.txt', 'passbook1.png': 'uploads/29c97177-75dd-4433-a2e1-3999d6c8303a/passbook1.png'}
2025-08-18 12:41:41,080 [INFO] 🤖 Step-1: Getting scrap code and metadata from llm. Tries count = 0
2025-08-18 12:41:52,540 [INFO] 🤖 Step-1: Successfully parsed response from LLM.
2025-08-18 12:41:52,540 [INFO] 💻 Step-3: Entering loop
2025-08-18 12:41:52,540 [INFO] 💻 Loop-1: Running LLM code.
2025-08-18 12:41:58,467 [INFO] ✅💻 Loop-1: Code executed successfully.
2025-08-18 12:41:58,467 [INFO] 🤖 Loop-1: Inside Loop LLM call.
2025-08-18 12:52:07,601 [INFO] 🤖 Loop-1: Inside Loop LLM call.
2025-08-18 12:52:19,799 [INFO] 💻 Loop-2: Running LLM code.
2025-08-18 12:52:28,927 [ERROR] ❌💻 Loop-2: Code execution failed: 131, in __call__ return wrapped_func(*args, **kwargs) File "/home/felicia/TDS_project2/venv/lib/python3.13/site-packages/google/api_core/retry/retry_unary.py", line 294, in retry_wrapped_func return retry_target( target, ...<3 lines>... on_error=on_error, ) File "/home/felicia/TDS_project2/venv/lib/python3.13/site-packages/google/api_core/retry/retry_unary.py", line 156, in retry_target next_sleep = _retry_error_helper( exc, ...<6 lines>... timeout, ) File "/home/felicia/TDS_project2/venv/lib/python3.13/site-packages/google/api_core/retry/retry_base.py", line 214, in _retry_error_helper raise final_exc from source_exc File "/home/felicia/TDS_project2/venv/lib/python3.13/site-packages/google/api_core/retry/retry_unary.py", line 147, in retry_target result = target() File "/home/felicia/TDS_project2/venv/lib/python3.13/site-packages/google/api_core/timeout.py", line 130, in func_with_timeout return func(*args, **kwargs) File "/home/felicia/TDS_project2/venv/lib/python3.13/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable raise exceptions.from_grpc_error(exc) from exc google.api_core.exceptions.NotFound: 404 models/gemini-pro-vision is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
2025-08-18 12:52:28,928 [INFO] 🤖 Loop-2: Inside Loop LLM call.
2025-08-18 12:52:32,584 [INFO] 🤖 Loop-2: Inside Loop LLM call.
2025-08-18 12:52:42,620 [INFO] 💻 Loop-3: Running LLM code.
2025-08-18 12:52:56,476 [INFO] ✅💻 Loop-3: Code executed successfully.
2025-08-18 12:52:56,476 [INFO] 🤖 Loop-3: Inside Loop LLM call.
2025-08-18 12:53:33,206 [INFO] 💻 Loop-4: Running LLM code.
2025-08-18 12:53:48,889 [INFO] ✅💻 Loop-4: Code executed successfully.
2025-08-18 12:53:48,889 [INFO] ✅📁 Loop-4: Found result files.
2025-08-18 12:53:48,890 [INFO] 🤖 Loop-4: Checking result validity.
2025-08-18 12:54:09,048 [INFO] 💻 Loop-4: Re-running code as per validation result.
2025-08-18 12:54:09,048 [INFO] 💻 Loop-5: Running LLM code.
2025-08-18 12:54:19,415 [INFO] ✅💻 Loop-5: Code executed successfully.
2025-08-18 12:54:19,415 [INFO] ✅📁 Loop-5: Found result files.
2025-08-18 12:54:19,415 [INFO] 🤖 Loop-5: Checking result validity.
2025-08-18 12:54:34,032 [INFO] 💻 Loop-5: Re-running code as per validation result.
2025-08-18 12:54:34,032 [INFO] 💻 Loop-6: Running LLM code.
2025-08-18 12:54:43,662 [INFO] ✅💻 Loop-6: Code executed successfully.
2025-08-18 12:54:43,662 [INFO] ✅📁 Loop-6: Found result files.
2025-08-18 12:54:43,663 [INFO] 🤖 Loop-6: Checking result validity.
2025-08-18 12:54:54,512 [INFO] ✅ Loop-6: Validation successful, no re-run needed.
2025-08-18 12:54:54,512 [INFO] 💻 Step-6: Running final code.
2025-08-18 12:54:54,529 [INFO] 📁 Step-7: Reading result.json
2025-08-18 12:54:54,529 [INFO] ✅📁 Step-7: send result back
